-- 코드를 입력하세요
SELECT 
    A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK B 
JOIN AUTHOR A USING(AUTHOR_ID)
JOIN BOOK_SALES USING(BOOK_ID)
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 1, 3 
ORDER BY 1, 3 DESC