-- 코드를 작성해주세요
SELECT 
    ID,
    CASE WHEN SIZE_RANK <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.25) THEN 'CRITICAL'
         WHEN SIZE_RANK <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.5) THEN 'HIGH'
         WHEN SIZE_RANK <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.75) THEN 'MEDIUM'
         ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_RANK
      FROM ECOLI_DATA
     ) AS SOR
ORDER BY ID