-- 코드를 입력하세요
-- 년, 월, 성별 별 상품을 구매한 회원 수
SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO 
JOIN ONLINE_SALE USING(USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;