-- 코드를 입력하세요
SELECT ANIMAL_TYPE, CASE 
    WHEN ANIMAL_TYPE LIKE 'Cat' THEN COUNT(*)
    WHEN ANIMAL_TYPE LIKE 'Dog' THEN COUNT(*)
    END AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE
