-- 코드를 입력하세요
WITH AVA_CAR AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT 
    A.CAR_ID,
    CASE 
        WHEN B.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS A
LEFT JOIN AVA_CAR AS B USING(CAR_ID)
ORDER BY CAR_ID DESC;