-- 코드를 입력하세요
-- CAR_TYPE = '트럭'
-- HISTORY_ID와 대여 금액 리스트 DAILY_FEE * DISCOUNT_RATE * DATEDIFF(START_DATE, END_DATE) AS FEE 출력
-- DAILY_FEE * (1 - DISCOUNT_RATE/100) * DATEDIFF(START_DATE, END_DATE) AS FEE
-- FEE의 경우 예시처럼 정수부분만 출력
-- FEE 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬
SELECT 
    HISTORY_ID,
    ROUND(
        DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상') / 100
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상') / 100
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN 1 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상') / 100
            ELSE 1
        END, 0) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
WHERE 
    CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, HISTORY_ID DESC;
