-- 코드를 입력하세요
WITH RECURSIVE cte(n) AS
(
    SELECT 0
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 23
)
SELECT 
    n AS HOUR, 
    COUNT(ANIMAL_ID) AS 'COUNT'
FROM cte 
LEFT JOIN ANIMAL_OUTS ON n = HOUR(DATETIME)
GROUP BY n
ORDER BY n;