-- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
JOIN ITEM_INFO I USING(ITEM_ID)
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID
                         FROM ITEM_INFO
                         WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;
