-- 코드를 작성해주세요
SELECT 
    C.ID, C.GENOTYPE, 
    P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C 
JOIN ECOLI_DATA AS P 
WHERE 
    C.GENOTYPE & P.GENOTYPE = P.GENOTYPE AND
    C.PARENT_ID = P.ID
ORDER BY ID
