-- 코드를 작성해주세요
WITH DIV_YEAR AS(
    SELECT MAX(SIZE_OF_COLONY) AS MAXSIZE,
    YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR)

SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    Y.MAXSIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA E
LEFT JOIN DIV_YEAR Y ON Y.YEAR = YEAR(DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV